#!/bin/sh

repo_name="project"
repo_path="/data/git/project.git"
script_path="/data"

while read oldrev newrev ref
do
    python3 $script_path/send-commit.py $repo_name $repo_path $ref $oldrev $newrev
done
